import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Cormorant_Garamond,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import "./ticker.css";
import MouseTracker from "@/components/MouseTracker";
import DownloadBrochure from "@/components/DownloadBrochure";
import WhatsAppWidget from "@/components/WhatsAppWidget";
import Navbar from "@/components/Navbar";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Precision Drying",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorantGaramond.variable} ${playfairDisplay.variable} h-full antialiased`}
      style={{
        fontFamily: "var(--font-cormorant-garamond), serif",
        backgroundColor: "#FFFFFF",
      }}
    >
      <body className="min-h-full flex flex-col font-serif">
        <MouseTracker />
        <Navbar />
        <DownloadBrochure />
        <WhatsAppWidget />
        {children}
      </body>
    </html>
  );
}
